title: Slides for 2019 talks - Bérénice Batut
email: berenice.batut@gmail.com
description: >
  This repository served the slides for my talks of 2019
repository: bebatut-slides/2019
twitter: bebatut
linkedin: berenicebatut
gitter: bebatut
orcid: 0000-0001-9852-1987
